using Borlay.Iota.Library.Utils;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Collections.Generic;
using System.Text;

namespace Borlay.Iota.Library.Tests
{
    [TestClass]
    public class UtilityTests
    {
        private readonly string intx = "9FLYWPOTEKSCYNJFXIORQOSTSCQNCVXNNIIKCPAUQ99LUIXZGUOXMJPALRCRCMVLZF9GRTYFJDUOOFSSGXBSEWIJWYCJWAIONLYCUZWAWCLLEK9TNHATRTOGE9BCUPKVQVKWBTPFFORIKNRVZQJVROWUMJ9AU9YLUUIDNTWDHXL9HSBMWGTFV9MTSTWRAQXYZRUCVTGWFKCBBAGFOYHZEDWUAMKVLZUIN9QQNPQEKRVNHPFEMCCA99GOQOOPHTYQDLPEFOISGIS9MJEEIWNFINBQPSKD9MRPHRYQGSRHJLIWUCUGXNZMVRMOUYONAISHOUMKTZM9LSNQMRXVYQPSQQXUGKYUSXSQOJOFRXMTUADZA9VHYGGJTKDMHRVIRZFSZAMNBOEIB9ELATY9ZG9WDSXY9OLTHRAKZUPGGQ9DK9LMMZPCASURAMKNQLIFBWJDMYULHMIRVUIKBLZSNMHXIKGVVUDJTJRYWEBVKKGXLHMDITFW9HRABHQZOJHCMRGNXSUVRLKUL9FTDRHQTJUQJSMSMVCVDVYZDALAKPQOAMEQKVEWQCYYKLVXCIEJLSDHONARSUDJECITQCHWKHJZYVFLCGMOUNTRQAWAGPKPTHPELBJXFFDROXUXQOXNYEXGJZBBZCBKYZ9O9GWCSXLZCLFPBPFSFFQUUMAGOMXOAWLEBPDEPDLU9ZENHFVQURAYVLFEFVSGPHKNYMWDZUOKTUUDIBZBEKI9SGJPZGUMGEBXUKVKD9SZISZJZSSEVAM9DXAVRVMXHXZ9LVQQZDAVPOPINZRRQZIBA9NLETMHXBQINWD9BCRASRBCKSSXUNEJPRKPETMQGNZFEGNMXUSQEIRKIVLEXCNNQVQFTVNTFEVYOQKBD9B9YRGFTIAHOMBLJMSHUNCKVGVERLXJWYJ9GYNASJXTQSZBAFGLUVVZMSCOGPKRJTINBAKCHOLRGWFY9GHMYBOXLXKNTIPBOKWTFUIBIIUKAZWMVGJBZVHGUBBTIKHQM9FMIDMMPOXFEZPSPNOHRWUXNWRNFRHQURHDODWEHRYSAKOBGWFZR9HXGNGVQPXRGFVTFBIQF9LYUN9RLZC9ADYBSQFKGSAGHAWMSNRYHMLMATSTEOYEMUIMQHSSNKT9RAQNNENKANHENCTSNMHNCKIIBGCAXHYAVSHJIZQVTSEPTILQDVXHBHTSVNDYEQOFPJSKWJKOGRGMWZMM9ZH9IEEQMJURFXVUDPHWWLJLKNOYDQIUBMWYQACLVIIIDHYRXJSR9YAFUAXC9DLUSAZYCTUVR9PPNKVYIRFQQBSVYLMVBJYQLHZRJTCJPSFDKZMGOWCWRYOKFPFWJWUCHG9WRHRDZKNNJQFZRNGMTLPXAMSR9TRRSREPBPESPBLLDQLAYWUGLXMU9BFFHXXKYWGMJCH9FSXRYQBLIXGHIZPW9VMGFDHKU9XKW9EAKKNWY9SXYEQXHNWSRLVRWOXCQTLUFQWFPBPHDYMRDZAOG9XRFZMFYFQJGOOERVQHQ9QTROGHIZTPSDAGQAJBXKWUJEAYWZHIOPYWXWTFKRZABOSESMNPBNPKBBMEOSMIKAJGDHGKXXLVNVYCHWALROEVMFVWT9YVVLGUATQJXUPIXS9FGNFRJGUHHBLGMUOUMCMIRKPRIOQTJ9RJHASGYAP9XRYWFXBBQMUWLTTVBGJDKZKIZCXBBYMGADZNXPJACDF9GBNB9DVVQRO9IXBXIWSPMKX9UTIRPNIBMUP9JPIRHPAFUNQGYOGLAGF9LQR9FNZXPHLHIXABQFSWTNWFSQAYM9U9VOKKGFVORGIWUHQOZRBG9CVEUGPJGUJJOL9IL9XNPMHNPNUIMPZCYTKDLQYJCNUGEOBWSRJFIJ9AUXGMJ9BUMPQOUZTWACPZTVF9WQSVBHBIGIWFITXHBUHBFEOYJEVGPLFIVVNQWPDIGTCIUHBRBBQISIMXYTPPDCW9OCNIGOKPQRPGGGFZOEKAMOABLSBKEEXXPVXKAWKPZLKBOQRGXNA9ZPRETFPYTMJYYYTAINHAL9EINMRUARVKAMSIHSBORAUZFELNMOVNNMLNGQSW9ZHYTVVHFJPYNVBMRJ9IWHCL9RPQTIJFYYJLLZPZY9CNIRFAXUMGVXZNSWZVQCAHFCLIXCTCUOQTTJMXDWSXJYOBFLQHWBERQCDPJTKFAZBEEEDFXNAKPWCHICGJZXKE9GSUDXZYUAPLHAKAHYHDXNPHENTERYMMBQOPSQIDENXKLKCEYCPVTZQLEEJVYJZV9BWU9999999999999999999999999999QGE99999999999999999999999XVCLMWD99999999999A99999999LBIGONFZ9HYFOKRGVATTEWCJOROZQOZURCIUSCRLOLQVPJNJQFXSVWVGYVTSPQSJLFQIGQOFWJ9RJYKIRI9MZQJ9ASULCYNCDGCITNOZUYNCEPBQAJZLVKJQSWJPVKKSOKNFZVWBBOJBNZQGL9F9ZRPBYAKLU99999KGUGQF9TKLRURJROCZKFZGPJDGHUDBJIIZARATGKPKWDCQOLHVLFR9DNAQF9L9F9KQFUBXSC9XO999999BID9TOBGUBEC9LOQIAZEDTVAZHZBAVLPIKXTAFCLAHMDCM9TZLYACQRAXAJUKYR9BFLXDMGBUWXIMHLQI";
        private readonly string outtx = "9FLYWPOTEKSCYNJFXIORQOSTSCQNCVXNNIIKCPAUQ99LUIXZGUOXMJPALRCRCMVLZF9GRTYFJDUOOFSSGXBSEWIJWYCJWAIONLYCUZWAWCLLEK9TNHATRTOGE9BCUPKVQVKWBTPFFORIKNRVZQJVROWUMJ9AU9YLUUIDNTWDHXL9HSBMWGTFV9MTSTWRAQXYZRUCVTGWFKCBBAGFOYHZEDWUAMKVLZUIN9QQNPQEKRVNHPFEMCCA99GOQOOPHTYQDLPEFOISGIS9MJEEIWNFINBQPSKD9MRPHRYQGSRHJLIWUCUGXNZMVRMOUYONAISHOUMKTZM9LSNQMRXVYQPSQQXUGKYUSXSQOJOFRXMTUADZA9VHYGGJTKDMHRVIRZFSZAMNBOEIB9ELATY9ZG9WDSXY9OLTHRAKZUPGGQ9DK9LMMZPCASURAMKNQLIFBWJDMYULHMIRVUIKBLZSNMHXIKGVVUDJTJRYWEBVKKGXLHMDITFW9HRABHQZOJHCMRGNXSUVRLKUL9FTDRHQTJUQJSMSMVCVDVYZDALAKPQOAMEQKVEWQCYYKLVXCIEJLSDHONARSUDJECITQCHWKHJZYVFLCGMOUNTRQAWAGPKPTHPELBJXFFDROXUXQOXNYEXGJZBBZCBKYZ9O9GWCSXLZCLFPBPFSFFQUUMAGOMXOAWLEBPDEPDLU9ZENHFVQURAYVLFEFVSGPHKNYMWDZUOKTUUDIBZBEKI9SGJPZGUMGEBXUKVKD9SZISZJZSSEVAM9DXAVRVMXHXZ9LVQQZDAVPOPINZRRQZIBA9NLETMHXBQINWD9BCRASRBCKSSXUNEJPRKPETMQGNZFEGNMXUSQEIRKIVLEXCNNQVQFTVNTFEVYOQKBD9B9YRGFTIAHOMBLJMSHUNCKVGVERLXJWYJ9GYNASJXTQSZBAFGLUVVZMSCOGPKRJTINBAKCHOLRGWFY9GHMYBOXLXKNTIPBOKWTFUIBIIUKAZWMVGJBZVHGUBBTIKHQM9FMIDMMPOXFEZPSPNOHRWUXNWRNFRHQURHDODWEHRYSAKOBGWFZR9HXGNGVQPXRGFVTFBIQF9LYUN9RLZC9ADYBSQFKGSAGHAWMSNRYHMLMATSTEOYEMUIMQHSSNKT9RAQNNENKANHENCTSNMHNCKIIBGCAXHYAVSHJIZQVTSEPTILQDVXHBHTSVNDYEQOFPJSKWJKOGRGMWZMM9ZH9IEEQMJURFXVUDPHWWLJLKNOYDQIUBMWYQACLVIIIDHYRXJSR9YAFUAXC9DLUSAZYCTUVR9PPNKVYIRFQQBSVYLMVBJYQLHZRJTCJPSFDKZMGOWCWRYOKFPFWJWUCHG9WRHRDZKNNJQFZRNGMTLPXAMSR9TRRSREPBPESPBLLDQLAYWUGLXMU9BFFHXXKYWGMJCH9FSXRYQBLIXGHIZPW9VMGFDHKU9XKW9EAKKNWY9SXYEQXHNWSRLVRWOXCQTLUFQWFPBPHDYMRDZAOG9XRFZMFYFQJGOOERVQHQ9QTROGHIZTPSDAGQAJBXKWUJEAYWZHIOPYWXWTFKRZABOSESMNPBNPKBBMEOSMIKAJGDHGKXXLVNVYCHWALROEVMFVWT9YVVLGUATQJXUPIXS9FGNFRJGUHHBLGMUOUMCMIRKPRIOQTJ9RJHASGYAP9XRYWFXBBQMUWLTTVBGJDKZKIZCXBBYMGADZNXPJACDF9GBNB9DVVQRO9IXBXIWSPMKX9UTIRPNIBMUP9JPIRHPAFUNQGYOGLAGF9LQR9FNZXPHLHIXABQFSWTNWFSQAYM9U9VOKKGFVORGIWUHQOZRBG9CVEUGPJGUJJOL9IL9XNPMHNPNUIMPZCYTKDLQYJCNUGEOBWSRJFIJ9AUXGMJ9BUMPQOUZTWACPZTVF9WQSVBHBIGIWFITXHBUHBFEOYJEVGPLFIVVNQWPDIGTCIUHBRBBQISIMXYTPPDCW9OCNIGOKPQRPGGGFZOEKAMOABLSBKEEXXPVXKAWKPZLKBOQRGXNA9ZPRETFPYTMJYYYTAINHAL9EINMRUARVKAMSIHSBORAUZFELNMOVNNMLNGQSW9ZHYTVVHFJPYNVBMRJ9IWHCL9RPQTIJFYYJLLZPZY9CNIRFAXUMGVXZNSWZVQCAHFCLIXCTCUOQTTJMXDWSXJYOBFLQHWBERQCDPJTKFAZBEEEDFXNAKPWCHICGJZXKE9GSUDXZYUAPLHAKAHYHDXNPHENTERYMMBQOPSQIDENXKLKCEYCPVTZQLEEJVYJZV9BWU9999999999999999999999999999QGE99999999999999999999999XVCLMWD99999999999A99999999LBIGONFZ9HYFOKRGVATTEWCJOROZQOZURCIUSCRLOLQVPJNJQFXSVWVGYVTSPQSJLFQIGQOFWJ9RJYKIR111111111111111111111111111111111111111111111111111111111111111111111111111111111222222222222222222222222222222222222222222222222222222222222222222222222222222222999999999999999999999999999999999999999999999999999999999999999999999999999999999";
        private readonly string trunk = "1".PadLast(81);
        private readonly string branch = "2".PadLast(81);

        [TestMethod]
        public void GeneratedTryteTest()
        {
            var trytes = IotaApiUtils.GenerateRandomTrytes();
            Assert.AreEqual(81, trytes.Length);
            Assert.IsTrue(ContainsChars(trytes, Constants.TryteAlphabet));
            //Assert.IsTrue(ContainsChars(Constants.TryteAlphabet, trytes)); // sometimes can throw 
        }

        [TestMethod]
        public void SetApproveTrunkTransactionTest()
        {
            var result = intx.SetApproveTrunk(trunk);
            Assert.AreNotEqual(intx, result);
        }

        [TestMethod]
        public void SetApproveBranchTransactionTest()
        {
            var result = intx.SetApproveBranch(branch);
            Assert.AreNotEqual(intx, result);
        }

        [TestMethod]
        public void SetApproveBothTransactionTest()
        {
            var result = intx.SetApproveTransactions(trunk, branch);
            Assert.AreEqual(outtx, result);
        }

        [TestMethod]
        public void SetApproveBothSepTransactionTest()
        {
            var result = intx.SetApproveBranch(branch);
            result = result.SetApproveTrunk(trunk);
            result = result.SetApproveBranch(branch); // ensure that it didn't lost trunk

            Assert.AreEqual(outtx, result);
        }

        [TestMethod]
        public void GetBothTransactionTest()
        {
            var getTrunk = outtx.GetTrunkTransaction();
            var getBranch = outtx.GetBranchTransaction();

            Assert.AreEqual(trunk, getTrunk);
            Assert.AreEqual(branch, getBranch);
        }

        private bool ContainsChars(string value, string chars)
        {
            foreach(var v in value)
            {
                if (!chars.Contains(v.ToString()))
                    return false;
            }
            return true;
        }
    }
}
